server:
  port: 8080
  mode: debug
  read_timeout: 30
  write_timeout: 30
  max_header_bytes: 1048576

database:
  host: localhost
  port: 5434
  user: master_guide
  password: master_guide123
  dbname: master_guide
  sslmode: disable
  max_open_conns: 100
  max_idle_conns: 10
  conn_max_lifetime: 3600

redis:
  host: localhost
  port: 6380
  password: ""
  db: 0
  pool_size: 10
  min_idle_conns: 5

jwt:
  secret: "master-guide-jwt-secret-key-2024"
  expire_hours: 24
  refresh_expire_hours: 168

log:
  level: debug
  format: json
  output: stdout
  file_path: "./logs/app.log"

cors:
  allowed_origins:
    - "http://localhost:3000"
    - "http://localhost:8080"
    - "http://127.0.0.1:3000"
    - "http://127.0.0.1:8080"
  allowed_methods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
    - "OPTIONS"
  allowed_headers:
    - "Origin"
    - "Content-Type"
    - "Accept"
    - "Authorization"
    - "X-Requested-With"
  allow_credentials: true
  max_age: 86400

upload:
  max_file_size: 10485760
  allowed_types:
    - "image/jpeg"
    - "image/png"
    - "image/gif"
    - "application/pdf"
    - "text/plain"
  upload_path: "./static/uploads"

websocket:
  read_buffer_size: 1024
  write_buffer_size: 1024
  max_message_size: 512
  pong_wait: 60
  ping_period: 54
  write_wait: 10 